language: python
python:
  - "2.7"
  - "3.5"
install: 
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
script: 
  - coverage run --source=enigma setup.py test
after_success:
  - coveralls
